# Generated by Django 2.0.5 on 2018-05-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('shortname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField()),
                ('city_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('photo_url', models.TextField(blank=True, null=True)),
                ('how_to_find_us', models.TextField(blank=True, null=True)),
                ('event_name', models.CharField(max_length=100)),
                ('event_status', models.TextField()),
                ('event_time', models.DateTimeField()),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.TextField()),
                ('why', models.TextField(blank=True, null=True)),
                ('headcount', models.IntegerField(blank=True, null=True)),
                ('rating_average', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField()),
                ('rsvp_limit', models.IntegerField()),
                ('maybe_rsvp_count', models.IntegerField()),
                ('yes_rsvp_count', models.IntegerField()),
                ('waitlist_count', models.IntegerField()),
                ('fee_accepts', models.TextField()),
                ('fee_amount', models.FloatField(blank=True, null=True)),
                ('fee_required', models.BooleanField()),
                ('repinned', models.NullBooleanField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('description', models.TextField()),
                ('join_mode', models.TextField()),
                ('organizer_id', models.IntegerField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('visibility', models.TextField()),
                ('who', models.CharField(blank=True, max_length=50, null=True)),
                ('photo_photo_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'group_topic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('member_id', models.IntegerField(blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('member_name', models.CharField(max_length=50)),
                ('member_status', models.TextField()),
                ('joined', models.DateTimeField()),
                ('bio', models.TextField(blank=True, null=True)),
                ('city_name', models.CharField(blank=True, max_length=50, null=True)),
                ('visited', models.DateTimeField()),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModeratorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'moderator_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('urlkey', models.CharField(max_length=50)),
                ('topic_name', models.CharField(max_length=50)),
                ('parent_topic_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'topic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopicFollowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'topic_followed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('address_1', models.CharField(blank=True, max_length=200, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=200, null=True)),
                ('city_name', models.CharField(blank=True, max_length=50, null=True)),
                ('rating_average', models.FloatField()),
                ('rating_count', models.FloatField()),
            ],
            options={
                'db_table': 'venue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Websitemanager',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('joined', models.DateTimeField()),
                ('manager_type', models.TextField()),
            ],
            options={
                'db_table': 'websitemanager',
                'managed': False,
            },
        ),
    ]
