# Generated by Django 2.0.5 on 2018-05-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptopic',
            name='group',
        ),
        migrations.AddField(
            model_name='grouptopic',
            name='group_id',
            field=models.IntegerField(null=True),
        ),
    ]
