# Generated by Django 2.0.5 on 2018-05-12 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180512_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptopic',
            name='group_id',
        ),
        migrations.AddField(
            model_name='grouptopic',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Groups'),
        ),
    ]
