# Generated by Django 2.0.5 on 2018-05-16 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180512_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderatorcategory',
            name='user_id',
        ),
        migrations.AddField(
            model_name='moderatorcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Websitemanager'),
        ),
        migrations.AlterField(
            model_name='topicfollowed',
            name='member',
            field=models.IntegerField(),
        ),
    ]
