from django.urls import path

from . import views

urlpatterns = [
    path('', views.Auth, name='index'),
    path('user_login/', views.UserLogin, name='user_login'),
    path('user_logged/', views.UserLogged, name='user_logged'),
    path('<int:user_id>/', views.UserIndex, name='user_index'),
    path('<int:user_id>/category/', views.CategoryIndex, name='category_index'),
    path('<int:user_id>/category/<int:category_id>/',
         views.CategoryDetail, name='category_detail'),
    path('<int:user_id>/city/', views.CityIndex, name='city_index'),
    path('<int:user_id>/city/<str:city_name>/', views.CityDetail, name='city_detail'),
    path('<int:user_id>/topic/', views.TopicIndex, name='topic_index'),
    path('<int:user_id>/topic/<int:topic_id>/', views.TopicDetail, name='topic_detail'),
    path('<int:user_id>/<str:filt>/<int:filt_pk>/group/',
         views.GroupIndex, name='group_index'),
    path('<int:user_id>/<str:filt>/<str:filt_pk>/group/',
         views.GroupIndex, name='group_index'),
    path('<int:user_id>/group/<int:group_id>/', views.GroupDetail, name='group_detail'),
    path('<int:user_id>/<str:filt>/<int:filt_pk>/<int:page>/venue/',
         views.VenueIndex, name='venue_index'),
    path('<int:user_id>/<str:filt>/<str:filt_pk>/<int:page>/venue/',
         views.VenueIndex, name='venue_index'),
    path('<int:user_id>/venue/<int:venue_id>/', views.VenueDetail, name='venue_detail'),
    path('<int:user_id>/venue/<int:venue_id>/vote', views.VenueVote, name='venue_vote'),
    path('<int:user_id>/<str:filt>/<int:filt_pk>/<int:page>/member/',
         views.MemberIndex, name='member_index'),
    path('<int:user_id>/<str:filt>/<str:filt_pk>/<int:page>/member/',
         views.MemberIndex, name='member_index'),
    path('<int:user_id>/member/<int:member_id>/', views.MemberDetail, name='member_detail'),
    path('<int:user_id>/<str:filt>/<int:filt_pk>/<str:date>/event/',views.EventIndex,name='event_index'),
    path('<int:user_id>/<str:filt>/<str:filt_pk>/<str:date>/event/',views.EventIndex,name='event_index'),
    path('<int:user_id>/event/<str:event_id>/', views.EventDetail, name='event_detail'),
    path('<int:user_id>/event/<str:event_id>/vote', views.EventVote, name='event_vote'),
    path('<int:user_id>/event/<str:event_id>/join', views.EventJoin, name='event_join'),
]
